### ISSUE TITLE
How to delete an account?

### ISSUE THREAD

**Issue by Kocal** [perry-mitchell/npm-user-switch#1]
Hey, first let me thank you for this app. It's sooo useful when I need to switch between my personnal and society NPM account :+1: 

After [ESLint virus](https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes), npm decided to [revoke all tokens](https://status.npmjs.org/incidents/dn7c1fgrr7ng) as a security measure.

I wanted to delete and re-add all accounts into `npm-user-switch`, but I don't find a way to delete thoses accounts.

Does this feature exist?

Thanks

**Comment by perry-mitchell** [comment]
Hi! Thanks for making an issue. I was just having the same thought, when I wanted to delete my old account. I'll add the feature today!

**Comment by Kocal** [comment]
Great, thanks :slightly_smiling_face:

**Comment by perry-mitchell** [comment]
@Kocal Released in version 0.3.0. Thanks!

**Comment by Kocal** [comment]
That's working like a charm :sparkles:
