### ISSUE TITLE
Add support for showing which account is in use.

### ISSUE THREAD

**Issue by LvChengbin** [perry-mitchell/npm-user-switch#3]
Thank you for your project, it is really useful for me.

Can you add a future for showing which account is in use?
Mostly, I think I know that I am using one account but not quite sure about that, so if I can check it, it will save me lots of time for typing the password and choosing the account.

Thank you so much.

**Comment by perry-mitchell** [comment]
`npm whoami` does this. Obviously it's been some time since you asked, however.. 😅
